nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://jasmine.computer
  Theme: https://github.com/probberechts/cactus-dark

projects_url: http://jasmine.computer

customize:
    gravatar:
    logo:
        enabled: true
        width: 50
        height: 50
        url:
        gravatar: false
    favicon:
    social_links:
        github: https://github.com/paladique
        twitter: https://twitter.com/paladique
        linkedin: https://www.linkedin.com/in/jasminegreenaway/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
